spring.application.name=projeto-bingou
server.port=8089
server.servlet.context-path=/bingou

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.liquibase.change-log=classpath:config/liquibase/master.xml
spring.liquibase.enabled=true

primary.datasource.driverClassName=com.mysql.cj.jdbc.Driver
primary.datasource.jdbc-url=${APP_DATABASE_JDBC_URL:jdbc:mysql://u941_txy8PQW9KU:W6cVtX!%3DTseCzR3wt!t8yR!k@ca-01.astralcloud.com.br:3306/s941_bingou_test}
primary.datasource.username=${APP_DATABASE_JDBC_USER:u941_txy8PQW9KU}
primary.datasource.password=${APP_DATABASE_JDBC_PASSWORD:W6cVtX!=TseCzR3wt!t8yR!k}
