spring.application.name=projeto-bingou
server.port=8089
server.servlet.context-path=/bingou

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.liquibase.change-log=classpath:config/liquibase/master.xml
spring.liquibase.enabled=true

spring.datasource.url=jdbc:mysql://u941_txy8PQW9KU:W6cVtX!%3DTseCzR3wt!t8yR!k@ca-01.astralcloud.com.br:3306/s941_bingou_test
spring.datasource.username=u941_txy8PQW9KU
spring.datasource.password=W6cVtX!=TseCzR3wt!t8yR!k
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver